#!/usr/bin/env python
#coding=utf8
"""Install vim configration.
    1. cp vimrc ~/.vimrc
    2. cp -r indent ~/.vim/
    3. cp -r syntax ~/.vim/
    4. git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    5. start vim, run "BundleInstall"
    done.
"""
