#!/usr/bin/env sh

echo "COPY .vimrc"
cp vimrc ~/.vimrc

echo "COPY indent..."
mkdir .vim
cp -r indent ~/.vim/

echo "COPY syntax..."
cp -r syntax ~/.vim/

echo "INSTALL vundle"
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

echo "DONE."
