#!/usr/bin/env sh

echo "COPY .vimrc"
cp vimrc ~/.vimrc

echo "COPY indent..."
mkdir ~/.vim
mv indent ~/.vim/

echo "COPY syntax..."
mv syntax ~/.vim/

echo "INSTALL vundle"
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

echo "DONE."
